version: "2"
services:
  mariadb:
    image: mariadb:10.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_catalog
      MYSQL_USER: book
      MYSQL_PASSWORD: book
    restart: on-failure
    volumes:
      - ./data:/var/lib/mysql
